### ISSUE TITLE
Update Player Name change messaging

### ISSUE THREAD

**Issue by tealidragon** [chodyo/one-night-ultimate-werewolf#29]
Current:
`Updated player S3mlD-e6r's name from "" to "MyName"`

Should be:
`Update player name to MyName`

**Comment by chodyo** [comment]
IMO just make this a console.log or even console.debug. Eventually we'll have player icons or something (think jackbox) that will just display a representation of the player along with their name.

**Comment by sequestrian** [comment]
Merge into `client-home-server-parity` and completed with https://github.com/chodyo/one-night-ultimate-werewolf/pull/30
