### ISSUE TITLE
Night Action Choice Results

### ISSUE THREAD

**Issue by sequestrian** [chodyo/one-night-ultimate-werewolf#36]
Doppelganger, Lone wolf, Seer, Robber and Insomniac must know the result of night actions. Doppelganger will need to perform other actions, but the remaining role actions and results of Doppelganged role actions can be displayed prior to daybreak or in the DayScreen ¯\_(ツ)_/¯ but must be known.

**Comment by chodyo** [comment]
ack

**Comment by sequestrian** [comment]
A bit of both really.
