### ISSUE TITLE
Integrate React with Node

### ISSUE THREAD

**Issue by sequestrian** [chodyo/one-night-ultimate-werewolf#6]
Migrate existing functionality into client/screens/HomeScreen

**Comment by tealidragon** [comment]
Found this legit example:
Root Project:
https://github.com/endel/colyseus-react-example
Client source:  https://github.com/endel/colyseus-react-example/blob/master/js/main.js
Server source:  https://github.com/endel/colyseus-react-example/blob/master/server/chat_room.js
